### ISSUE TITLE
Parameterized tests

### ISSUE THREAD

**Issue by devans80** [Resurr3ction/cppbdd#2]
If you accept PR's would it be possible (pending permission from the company I work for) to send a patch to extend cppbdd to handle parameterized tests as well ?

**Comment by michaelvlach** [comment]
Absolutely, go right ahead!

**Comment by devans80** [comment]
@Resurr3ction great, thanks. Also see https://github.com/google/googletest/issues/2250

**Comment by michaelvlach** [comment]
Thanks, a colleague of mine tried to push this into gtest before and was declined sadly without any explanation. Maybe you will be more lucky!

**Comment by michaelvlach** [comment]
Found his original submission: https://github.com/google/googletest/issues/1594

**Comment by devans80** [comment]
My employer is asking if your project has a contribution agreement other than the MIT license ?

**Comment by michaelvlach** [comment]
What do you mean? MIT license is as free as you can get. What exactly is an issue?

**Comment by devans80** [comment]
> What do you mean? MIT license is as free as you can get. What exactly is an issue?

No worries, it's all good. I'll prepare the PR and should push it in the next few days.
Thanks

**Comment by devans80** [comment]
Issue addressed in https://github.com/Resurr3ction/cppbdd/pull/3

**Comment by devans80** [comment]
Thanks @Resurr3ction !
